### ISSUE TITLE
User registration failing due to key expiry regardless of requirement setting

### ISSUE THREAD

**Issue by necrobuffalo** [J4LP/newauth#1]
Title covers it for the most part. I've allowed the cache timers to expire with the same result. Will take a harder look at it within the next few days if I have a chance.

**Comment by adrien-f** [comment]
Hey @necrobuffalo, I'll give it a look this morning, thanks for the report!

**Comment by adrien-f** [comment]
Would you be able to give me an example of configuration stripped of credentials that you have ? Especially the `EVE` settings so that I could reproduce your issue. Feel free to send them to vadrin_hegirin@j4lp.com if you don't want it to be public.

**Comment by necrobuffalo** [comment]
Of course.

``` python
EVE = {
        'auth_name': 'Astaroth Heavy Industries',
        'requirements': {
            'internal': {'mask': 268435455, 'expires': True}, # have run this with expires set both to true and to false
            'ally': {'mask': 0, 'expires': True}
        },
        'alliances': [],
        'corporations': [98342575],
        'keys': [(1234, 'foobar')]
    }
```

Apart from that, the secret key, and the database settings, my settings.py is identical to settings_dist.py.

**Comment by necrobuffalo** [comment]
Not able to test currently, but I suspect models/api_key.py on line 88-90. I've been trying to register with a key with no expiration set, so more than likely mask_name is being set to 'ally' in which case key validation will always fail due to expires being set to true.

**Comment by adrien-f** [comment]
Accidentally a word in the commit message.

I wasn't parsing the expiration date which would always return None on `self.expires` and even if a valid requirement was found, it would still loop around, 0 <= 26843545 <= 26843545, and would take the last valid mask.

Now it goes like this:
- API mask is 26843545
- mask_name is None
- Begin loop
- api_mask > requirement|['mask'] (internal, 26843545)
- mask_name is internal
- api_mask > requirement['mask'] (ally, 0) but requirement['mask'] < requirements[mask_name]['mask']
- mask_name still is internal

Hope this clears out !

**Comment by necrobuffalo** [comment]
o7 sir. Am now able to get through to character selection, though both of the characters on the key show up as being allies rather than internal and the buttons don't do anything. That's probably a subject for another issue though, and I've got a bit more free time today so I'll see if I can't figure it out myself tonight.

**Comment by adrien-f** [comment]
Yuuup, the buttons are another thing and actually do nothing (procrastination) ! I'll get cracking!

**Comment by necrobuffalo** [comment]
Ha, you're not the only one procrastinating, I was going to work on it last night but I unanchored a tower instead.

**Comment by adrien-f** [comment]
Hey @necrobuffalo  ! You should get up to date (some settings changed be careful! I really need a changelog) as we fixed the issue with the characters registration !
