### ISSUE TITLE
Multigroup pinging doesn't work

### ISSUE THREAD

**Issue by ghoti** [J4LP/newauth#15]
Attempting to ping multiple groups pings only the first group listed

**Comment by abzde** [comment]
If you ping to two groups/scopes/contacts it pings to the full member list of both groups/scopes/contacts. If you ping to a mixture of groups/scopes/contacts it pings to only users that are members of both entities.

ex: you ping "Fweddit" and "Alliance Leadership" it only pings to Alliance Leadership members that are also Fweddit members.
This should ping to the full member list of both Fweddit and Alliance Leadership, right?
